# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Email
      run: git config --global user.email "lwatkins26@gunston.org"
    - name: Name
      run: git config --global user.name "Lucas Watkins"
    - name: Add
      run: git add bin/ -f
    - name: Commit
      run: git commit -m "Auto Build for Linux"
    - name: Push
      run: git push -f origin build 
